version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node
      - /usr/app/node/node_modules
    command: node main.js
    networks:
      - node-default-network
    tty: true
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - node-default-network

  db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nodeuser
    networks:
      - node-default-network

networks:
  node-default-network:
    driver: bridge